table DimDate
	lineageTag: 5c30cbc5-8ac2-4ee7-b33c-f6cae10f365c
	dataCategory: Time

	measure 'Total Sales SPLY Year' = ```
			
			YEAR (
			    MINX (
			        DATEADD ( 'DimDate'[FullDateAlternateKey], -1, YEAR ),
			        'DimDate'[FullDateAlternateKey]
			    )
			)
			
			```
		formatString: 0
		lineageTag: f2aadbb2-d176-439d-8e75-d8b01cb96d2e

	measure 'Total Sales Year' = ```
			
			YEAR(MAX('DimDate'[FullDateAlternateKey]))
			
			```
		formatString: 0
		lineageTag: 861ab487-2e40-4117-a900-bdd7a074858f

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 3c36fb41-980a-4f56-a470-98bfd488524e
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column FullDateAlternateKey
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: d285a64f-b8ff-4b77-99e1-b75e57edd3d0
		summarizeBy: none
		sourceColumn: FullDateAlternateKey

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DayNumberOfWeek
		dataType: int64
		formatString: 0
		lineageTag: e67dac61-0370-4757-8ff0-bc1fa9498d17
		summarizeBy: sum
		sourceColumn: DayNumberOfWeek

		annotation SummarizationSetBy = Automatic

	column EnglishDayNameOfWeek
		dataType: string
		lineageTag: dbfdda03-f899-49da-9166-8e852e0f96e3
		summarizeBy: none
		sourceColumn: EnglishDayNameOfWeek

		annotation SummarizationSetBy = Automatic

	column DayNumberOfMonth
		dataType: int64
		formatString: 0
		lineageTag: ac6ca237-7952-4699-9b41-7c209619038f
		summarizeBy: sum
		sourceColumn: DayNumberOfMonth

		annotation SummarizationSetBy = Automatic

	column DayNumberOfYear
		dataType: int64
		formatString: 0
		lineageTag: 3d07683b-17e8-4a8f-ab7f-c0a5e1938e11
		summarizeBy: sum
		sourceColumn: DayNumberOfYear

		annotation SummarizationSetBy = Automatic

	column WeekNumberOfYear
		dataType: int64
		formatString: 0
		lineageTag: 22fc4e1b-0d96-4d12-ab3f-32cfbc30b9e3
		summarizeBy: sum
		sourceColumn: WeekNumberOfYear

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: ff841d3a-4146-45b0-bcdd-febe309495e1
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthNumberOfYear
		dataType: int64
		formatString: 0
		lineageTag: 05b376ff-c457-4279-9547-ccc12aec6ec2
		summarizeBy: sum
		sourceColumn: MonthNumberOfYear

		annotation SummarizationSetBy = Automatic

	column CalendarQuarter
		dataType: int64
		formatString: 0
		lineageTag: 02c765f4-3731-4d6a-880c-441c2b8859ad
		summarizeBy: sum
		sourceColumn: CalendarQuarter

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: a318578b-ea29-4395-8e4d-de987a850dd1
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column CalendarSemester
		dataType: int64
		formatString: 0
		lineageTag: 4756ad2d-bfbb-4274-85f6-e7e810686ff9
		summarizeBy: sum
		sourceColumn: CalendarSemester

		annotation SummarizationSetBy = Automatic

	column FiscalQuarter
		dataType: int64
		formatString: 0
		lineageTag: dd69b1f4-698d-4734-83f2-b2a2b3576d77
		summarizeBy: sum
		sourceColumn: FiscalQuarter

		annotation SummarizationSetBy = Automatic

	column FiscalYear
		dataType: int64
		formatString: 0
		lineageTag: 5345998a-dcfa-4115-9780-c39c053efa7c
		summarizeBy: sum
		sourceColumn: FiscalYear

		annotation SummarizationSetBy = Automatic

	column FiscalSemester
		dataType: int64
		formatString: 0
		lineageTag: 99e80629-b53d-4aeb-a586-c01f45ed9e41
		summarizeBy: sum
		sourceColumn: FiscalSemester

		annotation SummarizationSetBy = Automatic

	partition DimDate = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("P:\Pearl Innovations\Fabric Project\Dimension_Tables\Cleanseddim\DimDate.csv"),[Delimiter=",", Columns=15, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DateKey", Int64.Type}, {"FullDateAlternateKey", type date}, {"DayNumberOfWeek", Int64.Type}, {"EnglishDayNameOfWeek", type text}, {"DayNumberOfMonth", Int64.Type}, {"DayNumberOfYear", Int64.Type}, {"WeekNumberOfYear", Int64.Type}, {"EnglishMonthName", type text}, {"MonthNumberOfYear", Int64.Type}, {"CalendarQuarter", Int64.Type}, {"CalendarYear", Int64.Type}, {"CalendarSemester", Int64.Type}, {"FiscalQuarter", Int64.Type}, {"FiscalYear", Int64.Type}, {"FiscalSemester", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"CalendarYear", "Year"}, {"EnglishMonthName", "Month"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

