table DimProductSubcategory
	lineageTag: 6607bccb-8087-4956-b0b2-b09e750064b4

	column ProductSubcategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 61e8dbf9-8d80-4f44-85f8-d45ccbe94fa5
		summarizeBy: none
		sourceColumn: ProductSubcategoryKey

		annotation SummarizationSetBy = Automatic

	column ProductSubcategoryAlternateKey
		dataType: int64
		formatString: 0
		lineageTag: 9750cef4-2b60-4f3f-a0c1-72f0b558986c
		summarizeBy: count
		sourceColumn: ProductSubcategoryAlternateKey

		annotation SummarizationSetBy = Automatic

	column ProductSubcategory
		dataType: string
		lineageTag: 50d2fdf2-819c-4918-b673-e91016fc1978
		summarizeBy: none
		sourceColumn: ProductSubcategory

		annotation SummarizationSetBy = Automatic

	column ProductCategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 186a77e0-f092-4012-a828-4cb147a9891c
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		annotation SummarizationSetBy = Automatic

	partition DimProductSubcategory = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("P:\Pearl Innovations\Fabric Project\Dimension_Tables\Cleanseddim\DimProductSubcategory.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductSubcategoryKey", Int64.Type}, {"ProductSubcategoryAlternateKey", Int64.Type}, {"ProductSubcategoryName", type text}, {"ProductCategoryKey", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"ProductSubcategoryName", "ProductSubcategory"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

