table DimProduct
	lineageTag: e281e5df-56f1-451e-b6ba-2c2b58bc4393

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 0e987439-180c-4e3c-b2cc-fd4058cb6463
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductAlternateKey
		dataType: string
		lineageTag: 0e12cd0f-fe07-4d51-8179-1d2318573af4
		summarizeBy: none
		sourceColumn: ProductAlternateKey

		annotation SummarizationSetBy = Automatic

	column ProductSubcategoryKey
		dataType: int64
		formatString: 0
		lineageTag: ffc6e1a6-b6e0-4fc2-a07d-948ceaa1bc84
		summarizeBy: none
		sourceColumn: ProductSubcategoryKey

		annotation SummarizationSetBy = Automatic

	column WeightUnitMeasureCode
		dataType: string
		lineageTag: 3decb56e-1e25-458d-ad7c-51162913d7ed
		summarizeBy: none
		sourceColumn: WeightUnitMeasureCode

		annotation SummarizationSetBy = Automatic

	column SizeUnitMeasureCode
		dataType: string
		lineageTag: 5013fd5a-b99a-4df3-8d83-e9a4bdf50c4c
		summarizeBy: none
		sourceColumn: SizeUnitMeasureCode

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: a827ebb8-e2ce-4c97-9d7a-d6d7c3c063c8
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column SpanishProductName
		dataType: string
		lineageTag: bd694a43-9757-4b47-9ebf-801fda32b8e8
		summarizeBy: none
		sourceColumn: SpanishProductName

		annotation SummarizationSetBy = Automatic

	column FrenchProductName
		dataType: string
		lineageTag: 5c716db1-0b3b-4b23-aa65-30066e0ab200
		summarizeBy: none
		sourceColumn: FrenchProductName

		annotation SummarizationSetBy = Automatic

	column StandardCost
		dataType: string
		lineageTag: 3a07c6dc-5019-4e69-a72b-0b1df9cfa1ab
		summarizeBy: none
		sourceColumn: StandardCost

		annotation SummarizationSetBy = Automatic

	column FinishedGoodsFlag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8c2ce0bb-fe99-407d-ad97-24d1fd2d690b
		summarizeBy: none
		sourceColumn: FinishedGoodsFlag

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: ca910959-d560-48c8-bfee-00d080d03dad
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column SafetyStockLevel
		dataType: int64
		formatString: 0
		lineageTag: 65b5f69e-b69c-4d2f-abfa-37131e3e9272
		summarizeBy: sum
		sourceColumn: SafetyStockLevel

		annotation SummarizationSetBy = Automatic

	column ReorderPoint
		dataType: int64
		formatString: 0
		lineageTag: 52c26d69-e6d2-435c-a95c-943bbee8aca0
		summarizeBy: sum
		sourceColumn: ReorderPoint

		annotation SummarizationSetBy = Automatic

	column ListPrice
		dataType: string
		lineageTag: 187bdbaa-d0f9-4a2e-b5f6-5ec38527dbe6
		summarizeBy: none
		sourceColumn: ListPrice

		annotation SummarizationSetBy = Automatic

	column Size
		dataType: string
		lineageTag: c15cf348-3469-41ab-bb3c-234fe70d36f0
		summarizeBy: none
		sourceColumn: Size

		annotation SummarizationSetBy = Automatic

	column SizeRange
		dataType: string
		lineageTag: cac19419-0239-443d-b894-912fa95499dc
		summarizeBy: none
		sourceColumn: SizeRange

		annotation SummarizationSetBy = Automatic

	column Weight
		dataType: int64
		formatString: 0
		lineageTag: 3e0c3a10-1a72-4b0b-af28-8d9c86ec4706
		summarizeBy: sum
		sourceColumn: Weight

		annotation SummarizationSetBy = Automatic

	column DaysToManufacture
		dataType: int64
		formatString: 0
		lineageTag: 86bebec5-d668-4452-92b1-696a9acd067f
		summarizeBy: sum
		sourceColumn: DaysToManufacture

		annotation SummarizationSetBy = Automatic

	column ProductLine
		dataType: string
		lineageTag: add85680-4abb-48f0-a872-e7e6d16c65fc
		summarizeBy: none
		sourceColumn: ProductLine

		annotation SummarizationSetBy = Automatic

	column DealerPrice
		dataType: string
		lineageTag: f6775e7f-e3fd-421e-900e-517b9af208b1
		summarizeBy: none
		sourceColumn: DealerPrice

		annotation SummarizationSetBy = Automatic

	column Class
		dataType: string
		lineageTag: a8abec1a-ffa6-4793-9fad-e7d5aca2cdcf
		summarizeBy: none
		sourceColumn: Class

		annotation SummarizationSetBy = Automatic

	column Style
		dataType: string
		lineageTag: 5c5db958-d159-45c4-a997-5afad226843a
		summarizeBy: none
		sourceColumn: Style

		annotation SummarizationSetBy = Automatic

	column ModelName
		dataType: string
		lineageTag: dbd29de5-47ae-42c6-a2a6-dd87967f4cf8
		summarizeBy: none
		sourceColumn: ModelName

		annotation SummarizationSetBy = Automatic

	column LargePhoto
		dataType: string
		lineageTag: 443d53d3-17bd-41a9-8de5-ae34a12d0da9
		summarizeBy: none
		sourceColumn: LargePhoto

		annotation SummarizationSetBy = Automatic

	column EnglishDescription
		dataType: string
		lineageTag: f5206de4-7ffe-4dcc-ab5a-f5afde9d6368
		summarizeBy: none
		sourceColumn: EnglishDescription

		annotation SummarizationSetBy = Automatic

	column FrenchDescription
		dataType: string
		lineageTag: c41111aa-bfdc-49f9-a23d-e7f8a4b6aec7
		summarizeBy: none
		sourceColumn: FrenchDescription

		annotation SummarizationSetBy = Automatic

	column ChineseDescription
		dataType: string
		lineageTag: 5b2c3f6d-470c-46c0-9f91-907129db2fde
		summarizeBy: none
		sourceColumn: ChineseDescription

		annotation SummarizationSetBy = Automatic

	column ArabicDescription
		dataType: string
		lineageTag: 680c7519-6be0-45c2-820b-3d730e29e45e
		summarizeBy: none
		sourceColumn: ArabicDescription

		annotation SummarizationSetBy = Automatic

	column HebrewDescription
		dataType: string
		lineageTag: 88d73fce-1bf2-4f03-bde7-701c52a497e8
		summarizeBy: none
		sourceColumn: HebrewDescription

		annotation SummarizationSetBy = Automatic

	column ThaiDescription
		dataType: string
		lineageTag: 03ee3d2e-5781-456a-b788-f84d9758eaa5
		summarizeBy: none
		sourceColumn: ThaiDescription

		annotation SummarizationSetBy = Automatic

	column GermanDescription
		dataType: string
		lineageTag: d2f7b850-047d-4e51-a328-219b5b401ef8
		summarizeBy: none
		sourceColumn: GermanDescription

		annotation SummarizationSetBy = Automatic

	column JapaneseDescription
		dataType: string
		lineageTag: 7f23f606-1257-4beb-b401-9bd776d7d757
		summarizeBy: none
		sourceColumn: JapaneseDescription

		annotation SummarizationSetBy = Automatic

	column TurkishDescription
		dataType: string
		lineageTag: de12153e-2814-44a0-afb3-50416a1a1a7b
		summarizeBy: none
		sourceColumn: TurkishDescription

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 9572e70f-aca8-4f28-9b3f-341ee1f1bab1
		summarizeBy: none
		sourceColumn: StartDate

		variation Variation
			isDefault
			relationship: b84ff399-f984-4728-8ed5-6b97568cb431
			defaultHierarchy: LocalDateTable_7cca0900-02b5-4290-aa9e-a84d6673c0d4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column EndDate
		dataType: string
		lineageTag: afd2b9b7-4567-41fb-b81a-045150cefaa7
		summarizeBy: none
		sourceColumn: EndDate

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 3663269b-a137-4cdc-888f-82bcdcb4c5be
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	partition DimProduct = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("P:\Pearl Innovations\Fabric Project\Dimension_Tables\Cleanseddim\DimProduct.csv"),[Delimiter=",", Columns=36, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductKey", Int64.Type}, {"ProductAlternateKey", type text}, {"ProductSubcategoryKey", type text}, {"WeightUnitMeasureCode", type text}, {"SizeUnitMeasureCode", type text}, {"EnglishProductName", type text}, {"SpanishProductName", type text}, {"FrenchProductName", type text}, {"StandardCost", type text}, {"FinishedGoodsFlag", type logical}, {"Color", type text}, {"SafetyStockLevel", Int64.Type}, {"ReorderPoint", Int64.Type}, {"ListPrice", type text}, {"Size", type text}, {"SizeRange", type text}, {"Weight", Int64.Type}, {"DaysToManufacture", Int64.Type}, {"ProductLine", type text}, {"DealerPrice", type text}, {"Class", type text}, {"Style", type text}, {"ModelName", type text}, {"LargePhoto", type text}, {"EnglishDescription", type text}, {"FrenchDescription", type text}, {"ChineseDescription", type text}, {"ArabicDescription", type text}, {"HebrewDescription", type text}, {"ThaiDescription", type text}, {"GermanDescription", type text}, {"JapaneseDescription", type text}, {"TurkishDescription", type text}, {"StartDate", type datetime}, {"EndDate", type text}, {"Status", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"EnglishProductName", "Product"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"ProductSubcategoryKey", Int64.Type}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

